
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mini?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xmbcit

  redis:
    database: 0 # 表示使用redis通统一数据库
    host: localhost
    port: 6379

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.meitu.mini1.entities